---
title: "scrapbase"
output: html_document
date: "2025-09-28"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```
##Analysis by Region
This section looks explores the dataset grouped the the WHO defined 'regions' which are: 
-Africa
-The Americas
-South East Asia region
-Europe
-East Mediterranean region
-West Pacific region

Please use the who_data.csv file in the repository for this section
```{r}
library(dplyr)
data <- data.frame(read.csv("\\Users\\ilc04\\OneDrive - University of Bristol\\DST\\who_data.csv"))
data <- data[-c(6,14,15,17)] #removing empty columns
```

```{r}
summary(data)
numeric_df <- data[sapply(data,is.numeric)]#separating numeric columns

```



```{r}
df_eu <- data[data$who_region=='4_Eur',]
df_amr <- data[data$who_region=='2_Amr',]
summary(df_amr)
```

```{r}
summary(df_eu)
```

```{r}
# Count missing values in each column using sapply()
regional_numeric <- numeric_df
regional_numeric$who_region <- data$who_region
afr_nas<- sapply(regional_numeric[regional_numeric$who_region=='1_Afr',], function(x) sum(is.na(x)))
afr_nas <- (afr_nas/nrow(regional_numeric[regional_numeric$who_region=='1_Afr',]))*100
                            
amr_nas <- sapply(regional_numeric[regional_numeric$who_region=='2_Amr',], function(x) sum(is.na(x)))
amr_nas <- (amr_nas/nrow(regional_numeric[regional_numeric$who_region=='2_Amr',]))*100

sear_nas <- sapply(regional_numeric[regional_numeric$who_region=='3_Sear',], function(x) sum(is.na(x)))
sear_nas <- (sear_nas/nrow(regional_numeric[regional_numeric$who_region=='3_Sear',]))*100

eur_nas <- sapply(regional_numeric[regional_numeric$who_region=='4_Eur',], function(x) sum(is.na(x)))
eur_nas <- (eur_nas/nrow(regional_numeric[regional_numeric$who_region=='4_Eur',]))*100

emr_nas <- sapply(regional_numeric[regional_numeric$who_region=='5_Emr',], function(x) sum(is.na(x)))
emr_nas <- (emr_nas/nrow(regional_numeric[regional_numeric$who_region=='5_Emr',]))*100

wpr_nas <- sapply(regional_numeric[regional_numeric$who_region=='6_Wpr',], function(x) sum(is.na(x)))
wpr_nas <- (wpr_nas/nrow(regional_numeric[regional_numeric$who_region=='6_Wpr',]))*100

missing_vals <- data.frame(afr = afr_nas, amr = amr_nas, sear = sear_nas, eur = eur_nas, emr= emr_nas, wpr = wpr_nas)
pm10 <- as.numeric(missing_vals[2,])
pm25 <- as.numeric(missing_vals[3,])
no2 <- as.numeric(missing_vals[4,])

barplot(height = pm10, names.arg = colnames(missing_vals), xlab = "WHO Region", ylab = "Percentage of missing data", main = "pm10 concentration missing data")
barplot(height = pm25, names.arg = colnames(missing_vals), xlab = "WHO Region", ylab = "Percentage of missing data", main = "pm25 concentration missing data")
barplot(height = no2, names.arg = colnames(missing_vals), xlab = "WHO Region", ylab = "Percentage of missing data", main = "no2 concentration missing data")

```
```{r}

```



